spring:
  application:
    name: LuaBridge

  datasource:
    url: jdbc:postgresql://localhost:5432/luacoffe
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update  # Pode ser "none", "update", "create", "create-drop"
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true  # Exibe as consultas SQL no log
